# Generated by Django 3.2.8 on 2021-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_model', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
