# Generated by Django 3.2.8 on 2021-11-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgnapp', '0002_alter_servicedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
