# Generated by Django 3.2.8 on 2021-11-01 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fgnapp', '0003_alter_servicedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
